#! /bin/bash

wifipasswd=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1 | tr -d ' ' | tr -d '\n'`
echo "Wifi password in `date +%d/%m/%Y` is: $wifipasswd" | mail -s "Wifi Password Today" "${1}"
./chgWifiPasswd "$wifipasswd"
